import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light overflow-x-hidden">

      <body className={inter.className}>
        <Toaster/>
        <div className="absolute z-50 top-0 py-5 container left-0 right-0 mx-auto"><Navbar></Navbar></div>
        <div>{children}</div>
         <Footer/>
      </body>
    </html>
  );
}
